---
title: "P8105_hw4_problem2"
author: "Nadiya Pavlishyn"
date: "10/26/2017"
output: html_document
---

Nadiya Pavlishyn (np2547) as project lead and Feben Asefaha (fta2112) as collaborator
```{r}
library(dplyr)
library(readr)
library(tidyverse)

gdp_table = read_csv("./data/GDP.csv")

#change . in value to na
gdp_table$VALUE[gdp_table$VALUE == "."] <- NA
  

pols_month = read_csv("./data/pols-month.csv") %>%
  mutate(president = prez_gop) %>%
  select(-prez_gop) 

#change binary 01 values to more appropriate ones
pols_month$president = ifelse(pols_month$president == 0, "dem", "gop")


#floor_date 
pols_month$mon = lubridate::floor_date(pols_month$mon, unit = "month")
gdp_table$DATE = lubridate::floor_date(gdp_table$DATE, unit = "month")

#change pols_month mon column to DATE, change VALUE to gdp for clarity
#colnames(pols_month)[1] <- "DATE"
#colnames(gdp_table)[2] <- "gdp"

pols_month = rename(pols_month, DATE = mon) 
gdp_table = rename(gdp_table, gdp = VALUE) 

#combine datasets 
pols_gdp = full_join(pols_month, gdp_table, by = "DATE")

#since we are plotting  this dataset, omit na's
pols_gdp = pols_gdp %>% 
  na.omit(gdp)
```


```{r graphing}

#converting gdp to numeric 
pols_gdp = pols_gdp %>% 
  mutate(gdp = as.numeric(gdp))

str(pols_gdp)

library(ggplot2)
library(ggridges)
library(scales)


  #scale_x_datetime(breaks=date_breaks("10 year"), labels=date_format("%Y:%m")) + 
  #theme(axis.text.x=element_text(angle=90))

ggplot(pols_gdp, aes(x = DATE, y = gdp)) + 
  geom_point(aes(color = president)) +
  scale_color_manual(values = c("blue", "red")) +
scale_y_continuous(breaks = seq(-4, 20, by = 2)) +
  scale_x_date(breaks=date_breaks("5 year"),
               labels = date_format("%Y"))

```

```{r graph 2}

ggplot(pols_gdp, aes(x= DATE, y= gdp, fill= president)) + 
  geom_bar(stat="identity")

```





